//! Required validation order (specs/IPC.md).
//!
//! The platform transport identifies the native caller, then this module
//! performs the remaining checks in the mandated order. Application command
//! code must never run before authorization and decode validation complete.

use crate::caller::CallerId;
use crate::capabilities::CapabilityBits;
use crate::error::Error;
use crate::header::{ControlFlags, ControlHeader};
use crate::limits::Limits;

/// Result of the validation pipeline for a single request.
#[derive(Debug)]
pub struct ValidatedRequest {
    pub caller: CallerId,
    pub command_id: u32,
    pub request_id: u64,
    /// Declared payload length from the header.
    pub payload_len: u32,
    pub codec: u16,
}

/// Validates the outer message type and protocol version before any
/// command-specific work happens.
pub fn validate_outer_header(header: &ControlHeader) -> Result<(), Error> {
    header.validate().map_err(Error::protocol_error)?;
    if header.flags & ControlFlags::REQUEST.bits() == 0 {
        return Err(Error::protocol_error("message is not a control request"));
    }
    Ok(())
}

/// Checks the command ID against the registered manifest. The manifest
/// function is generated by kiri-codegen; for now a caller-supplied closure
/// stands in and unknown IDs are rejected here, before application logic.
pub fn validate_command_id(
    command_id: u32,
    is_known: impl FnOnce(u32) -> bool,
) -> Result<(), Error> {
    if !is_known(command_id) {
        return Err(Error::protocol_error(format!("unknown command id {command_id}")));
    }
    Ok(())
}

/// Validates the declared payload length against the actual representation.
pub fn validate_payload_length(declared: u32, actual: u32, limits: &Limits) -> Result<(), Error> {
    if declared != actual {
        return Err(Error::protocol_error(format!(
            "declared payload length {declared} does not match actual {actual}"
        )));
    }
    limits.check_control_payload(actual)
}

/// Authorization step (specs/SECURITY.md step 3): test the coarse capability
/// bit. Scope validation is step 4 and happens in the command implementation.
pub fn authorize_capability(
    granted: &CapabilityBits,
    required: CapabilityBits,
) -> Result<(), Error> {
    if !granted.is_superset_of(&required) {
        return Err(Error::unauthorized("caller lacks required capability"));
    }
    Ok(())
}

/// Run the full pipeline for an already-caller-identified request.
///
/// Order (specs/IPC.md): outer type -> version -> command id -> payload
/// length -> authorize. Decode and execute are the caller's next steps.
pub fn validate_request(
    caller: CallerId,
    header: &ControlHeader,
    actual_payload_len: u32,
    granted: &CapabilityBits,
    required: CapabilityBits,
    limits: &Limits,
    is_known: impl FnOnce(u32) -> bool,
) -> Result<ValidatedRequest, Error> {
    validate_outer_header(header)?;
    validate_command_id(header.command_id, is_known)?;
    validate_payload_length(header.payload_len, actual_payload_len, limits)?;
    authorize_capability(granted, required)?;
    Ok(ValidatedRequest {
        caller,
        command_id: header.command_id,
        request_id: header.request_id,
        payload_len: header.payload_len,
        codec: header.codec,
    })
}

/// Convenience: convert a validation failure into the trace result code that
/// should be attached to the closing trace event.
pub fn trace_result_code(err: &Error) -> &'static str {
    err.code.as_str()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::ErrorCode;
    use crate::header::MAGIC;
    use crate::limits::Limits;

    fn header_with(command_id: u32, payload_len: u32) -> ControlHeader {
        ControlHeader {
            magic: MAGIC,
            version: 1,
            flags: ControlFlags::REQUEST.bits(),
            command_id,
            request_id: 99,
            payload_len,
            codec: 1,
            reserved: 0,
            resource_count: 0,
        }
    }

    #[test]
    fn valid_request_passes_pipeline() {
        let caller = CallerId(1);
        let header = header_with(17, 64);
        let mut granted = CapabilityBits::empty();
        granted.set(3);
        let mut required = CapabilityBits::empty();
        required.set(3);
        let validated =
            validate_request(caller, &header, 64, &granted, required, &Limits::default(), |id| {
                id == 17
            })
            .unwrap();
        assert_eq!(validated.command_id, 17);
        assert_eq!(validated.request_id, 99);
        assert_eq!(validated.caller, caller);
    }

    #[test]
    fn unknown_command_id_rejected_before_application() {
        let header = header_with(999, 0);
        let err = validate_request(
            CallerId(1),
            &header,
            0,
            &CapabilityBits::empty(),
            CapabilityBits::empty(),
            &Limits::default(),
            |_| false,
        )
        .unwrap_err();
        assert_eq!(err.code, ErrorCode::ProtocolError);
    }

    #[test]
    fn malformed_payload_length_rejected() {
        let header = header_with(17, 100);
        let err = validate_request(
            CallerId(1),
            &header,
            50,
            &CapabilityBits::empty(),
            CapabilityBits::empty(),
            &Limits::default(),
            |_| true,
        )
        .unwrap_err();
        assert_eq!(err.code, ErrorCode::ProtocolError);
    }

    #[test]
    fn oversized_control_payload_rejected() {
        let header = header_with(17, 1024 * 1024 + 1);
        let err = validate_request(
            CallerId(1),
            &header,
            1024 * 1024 + 1,
            &CapabilityBits::empty(),
            CapabilityBits::empty(),
            &Limits::default(),
            |_| true,
        )
        .unwrap_err();
        assert_eq!(err.code, ErrorCode::LimitExceeded);
    }

    #[test]
    fn missing_capability_denied() {
        let header = header_with(17, 0);
        let mut granted = CapabilityBits::empty();
        granted.set(0);
        let mut required = CapabilityBits::empty();
        required.set(1);
        let err = validate_request(
            CallerId(1),
            &header,
            0,
            &granted,
            required,
            &Limits::default(),
            |_| true,
        )
        .unwrap_err();
        assert_eq!(err.code, ErrorCode::Unauthorized);
    }

    #[test]
    fn wrong_message_type_rejected() {
        let mut header = header_with(17, 0);
        header.flags = ControlFlags::RESPONSE.bits();
        let err = validate_outer_header(&header).unwrap_err();
        assert_eq!(err.code, ErrorCode::ProtocolError);
    }

    #[test]
    fn trace_result_code_maps_errors() {
        assert_eq!(trace_result_code(&Error::unauthorized("no")), "unauthorized");
    }
}
