//! Compile-time frontend (generated by `build.rs`).
//!
//! This is the disk-free path: `kiri-host` with no `--frontend` serves these
//! bytes over `kiri://`. On Windows the same bytes are materialized to a temp
//! folder because WebView2 virtual-host mapping requires a real directory.

use std::path::Path;

include!(concat!(env!("OUT_DIR"), "/embedded_frontend.rs"));

/// Look up a packed asset. `""` and `"/"` map to `index.html`.
pub fn get(request_path: &str) -> Option<&'static [u8]> {
    let key = normalize_key(request_path)?;
    EMBEDDED_FILES.iter().find(|(k, _)| *k == key).map(|(_, bytes)| *bytes)
}

pub fn has_index() -> bool {
    get("index.html").is_some()
}

pub fn file_count() -> usize {
    EMBEDDED_FILES.len()
}

/// Write every packed file under `dir`, creating parents as needed.
pub fn materialize(dir: &Path) -> std::io::Result<()> {
    for (rel, bytes) in EMBEDDED_FILES {
        let dest = dir.join(rel);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(dest, bytes)?;
    }
    Ok(())
}

/// Map `https://app.localhost/foo` to the packed key `foo` (or `index.html`).
pub fn request_path_from_https_origin(url: &str, origin: &str) -> Option<String> {
    let rest = url.strip_prefix(origin)?;
    let rest = rest.split(['?', '#']).next().unwrap_or(rest);
    let rest = rest.trim_start_matches('/');
    Some(if rest.is_empty() { "index.html".into() } else { rest.to_string() })
}

pub fn normalize_key(request_path: &str) -> Option<String> {
    let trimmed = request_path.trim_start_matches('/');
    if trimmed.is_empty() {
        return Some("index.html".into());
    }
    let mut parts: Vec<String> = Vec::new();
    for comp in std::path::Path::new(trimmed).components() {
        match comp {
            std::path::Component::Normal(c) => parts.push(c.to_string_lossy().into_owned()),
            _ => return None,
        }
    }
    Some(parts.join("/"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_embed_has_index_and_kiri_js() {
        assert!(has_index(), "examples/blank must pack index.html");
        assert!(get("kiri.js").is_some(), "examples/blank must pack kiri.js");
        assert!(file_count() >= 2);
    }

    #[test]
    fn traversal_is_rejected() {
        assert!(normalize_key("../etc/passwd").is_none());
        assert_eq!(normalize_key("/").as_deref(), Some("index.html"));
    }

    #[test]
    fn https_origin_maps_to_pack_keys() {
        assert_eq!(
            request_path_from_https_origin("https://app.localhost/", "https://app.localhost")
                .as_deref(),
            Some("index.html")
        );
        assert_eq!(
            request_path_from_https_origin(
                "https://app.localhost/kiri.js",
                "https://app.localhost"
            )
            .as_deref(),
            Some("kiri.js")
        );
        assert!(
            request_path_from_https_origin("https://evil.example/x", "https://app.local").is_none()
        );
    }
}
