//! Pack a frontend directory into the host binary (Tauri `frontendDist`
//! equivalent). Default is `examples/blank` so smoke/bench stay stable.
//! Override at compile time with `KIRI_EMBED_FRONTEND=/path/to/ui`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let default = manifest.join("../../examples/blank");
    let requested =
        env::var("KIRI_EMBED_FRONTEND").ok().filter(|s| !s.is_empty()).map(PathBuf::from);
    let root = match requested {
        Some(p) if p.is_dir() => p,
        Some(p) => panic!("KIRI_EMBED_FRONTEND is not a directory: {}", p.display()),
        None => default,
    };
    let root = root.canonicalize().unwrap_or(root);
    println!("cargo:rerun-if-env-changed=KIRI_EMBED_FRONTEND");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    walk(&root, &root, &mut files);
    if files.is_empty() {
        panic!("no frontend files packed from {}", root.display());
    }
    if !files.iter().any(|(rel, _)| rel == "index.html") {
        panic!("frontend is missing index.html: {}", root.display());
    }
    println!(
        "cargo:warning=kiri-runtime packed {} frontend files from {}",
        files.len(),
        root.display()
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("embedded_frontend.rs");
    let mut src = String::from(
        "// @generated by crates/kiri-runtime/build.rs. Do not edit.\n\
         pub static EMBEDDED_FILES: &[(&str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
        let abs_str = abs.to_str().expect("frontend path must be UTF-8");
        src.push_str(&format!("    ({rel:?}, include_bytes!({abs_str:?})),\n"));
    }
    src.push_str("];\n");
    fs::write(dest, src).expect("write embedded_frontend.rs");
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    let mut ents: Vec<_> = entries.filter_map(|e| e.ok()).collect();
    ents.sort_by_key(|e| e.file_name());
    for ent in ents {
        let name = ent.file_name();
        if name.to_string_lossy().starts_with('.') {
            continue;
        }
        let path = ent.path();
        if path.is_dir() {
            walk(root, &path, out);
            continue;
        }
        let rel = path.strip_prefix(root).unwrap().to_string_lossy().replace('\\', "/");
        out.push((rel, path));
    }
}
